services:

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      HOST_IP: ${HOST_IP} 
      # Databases are typically created by the DB import scripts,
      # so we don't set MYSQL_DATABASE here
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro   # Grant permission
      - ./mariadb/conf/my.cnf:/etc/mysql/conf.d/logging.cnf:ro
      - ./logs/mariadb:/var/log/mysql
    # ports:  # Database debug purpose
    #  - "3307:3306"
    networks:
      - wow-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  realmd:
    build:
      context: ./realmd
    container_name: wow-realmd
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./realmd/realmd.conf:/opt/realmd/realmd.conf:ro
      - ./data/patches:/opt/realmd/patches:ro
      - ./logs/realmd:/opt/realmd/logs
    ports:
      - "3724:3724"
    networks:
      - wow-net

  mangosd:
    build:
      context: ./mangosd
    container_name: wow-mangosd
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./mangosd/mangosd.conf:/opt/mangosd/mangosd.conf:ro
      - ./data/dbc:/opt/mangosd/dbc:ro
      - ./data/maps:/opt/mangosd/maps:ro
      - ./data/vmaps:/opt/mangosd/vmaps:ro
      - ./data/mmaps:/opt/mangosd/mmaps:ro
      - ./data/database_updates:/opt/mangosd/database_updates:ro
      - ./logs/mangosd:/opt/mangosd/logs
    ports:
      - "8085:8085"
    networks:
      - wow-net
    stdin_open: true   # keeps the mangosd console interactive
    tty: true

networks:
  wow-net:
    driver: bridge
